name: update CDN CIDR

# schedule every 5 minutes to update CDN CIDR
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  updateCDN:
    runs-on: ubuntu-latest
    
    steps:

      # https://github.com/actions/checkout
      - uses: actions/checkout@v3

      - name: download CDN CIDR
        run: |
          curl -s https://www.arvancloud.ir/fa/ips.txt > arvan_ipv4.txt
          curl -s https://www.cloudflare.com/ips-v4 > cloudflare_ipv4.txt
          curl -s https://www.cloudflare.com/ips-v6 > cloudflare_ipv6.txt
          curl -s https://ip-ranges.amazonaws.com/ip-ranges.json | jq ".prefixes[].ip_prefix" | sed 's/"//g' > aws_ipv4.txt
          curl -s https://ip-ranges.amazonaws.com/ip-ranges.json | jq ".ipv6_prefixes[].ipv6_prefix" | sed 's/"//g' > aws_ipv6.txt
          curl -s https://api.gcorelabs.com/cdn/public-ip-list | jq ".addresses[]" | sed 's/"//g' > gcore_ipv4.txt
          curl -s https://api.gcorelabs.com/cdn/public-ip-list | jq ".addresses_v6[]" | sed 's/"//g' > gcore_ipv6.txt
      
      - name: Get current date
        id: date
        #run: echo "::set-output name=date::$(TZ=Asia/Tehran date +'%s')"
        run: echo "date=$(TZ=Asia/Tehran date +'%Y/%m/%d %R')" >> $GITHUB_OUTPUT
      
      # https://github.com/stefanzweifel/git-auto-commit-action
      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          commit_message: "Update CDN CIDR at ${{ steps.date.outputs.date }}"
          commit_options: '--no-verify --signoff'
          commit_user_name: "mheidari98"
          commit_user_email: "mahdih3idari@gmail.com"
          # commit_author: Author <actions@github.com> 


      - name: Env
        run: |
          echo "TAG_NAME=$(TZ=Asia/Tehran date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(TZ=Asia/Tehran date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Create Release
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.txt"
          body: "Update CDN CIDR at ${{ steps.date.outputs.date }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
          

